version: '3.8'

services:
  
  postgressql_db:
    container_name: pg_container
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=documentDb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgres/data
    
    
  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=root
      ports:
        - "5050:80"
      restart: always
      volumes:
        - pgadmin:/root/.pgadmin
  
volumes:
    database-data:
    pgadmin:
